-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHmvgQ8f+dO2D8dOS
u0Tc+PEoFUCF/g8TUO7oA+WZ3oKgCgYIKoZIzj0DAQehRANCAAS7IYC1yicEH91C
TUoPTgF6nTYzl0FwXOBZkrqhp2QJEbENH+f1xZvCTuhBQgoz8znj07mY3ycnay/R
rE1LBOSS
-----END PRIVATE KEY-----